version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - cp target/*.jar banking.jar

artifacts:
  base-directory: .
  files:
    - banking.jar
    - .ebextension/**
  discard-paths: no
